# Generated by Django 5.2 on 2025-04-07 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.company'),
        ),
    ]
